### ISSUE TITLE
Sky-vault view fraction

### ISSUE THREAD

**Issue by grjonathan** [CenterForTheBuiltEnvironment/pythermalcomfort#10]
Add a function to calculate f_svv given window dimensions and the distance between the occupant and the window, as per equation C-7 in ASHRAE 55-2017. 
@FedericoTartarini I'm glad to work on this if you think it's a good idea.
![image](https://user-images.githubusercontent.com/51000403/101962931-5b442000-3bdb-11eb-8488-85edfc3c5604.png)

**Comment by FedericoTartarini** [comment]
Good suggestion, I added it to pythermalcomfort and released a new version [v.1.3.3](https://pypi.org/project/pythermalcomfort/1.3.3/)

[New f_svv function](https://pythermalcomfort.readthedocs.io/en/latest/reference/pythermalcomfort.html#pythermalcomfort.psychrometrics.f_svv)

Kindly let me know if you find any issues

**Comment by grjonathan** [comment]
Looks great!
