### ISSUE TITLE
Allow users to pass numpy arrays and Pandas Dataframes as input to the functions

### ISSUE THREAD

**Issue by FedericoTartarini** [CenterForTheBuiltEnvironment/pythermalcomfort#11]
Maybe have a look on how their are handling this in the scikit-learn packages and get some inspiration on how to write the code.

**Comment by grjonathan** [comment]
This would be nice. As a band-aid solution I have been using pandas [itertuples](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.itertuples.html), which seems to be much quicker than [iterrows](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iterrows.html?highlight=iterrows).

```
for row in data.itertuples():
    result = pmv_ppd(row.temp_indoor, row.mrt, row.v_relative, row.rh, row.met, row.clo)
    
    data.at[row.Index, 'pmv'] = result['pmv']
    data.at[row.Index, 'ppd'] = result['ppd']
```
Of course, that is not a substitute for accepting numpy arrays and Dataframes within the function itself.

**Comment by FedericoTartarini** [comment]
Thank you for sharing that. I have also used a similar solution in the [backend code](https://github.com/CenterForTheBuiltEnvironment/comfort_tool/blob/450b28eb23beedd6d7135711432740c2b3440e0c/comfort.py#L121) that calculates the thermal comfort indices in the Upload page of the CBE comfort tool. 

I have not yet implemented the functionality of allowing users to pass in data from a Pandas Dataframe since I was not sure on how to do it efficiently. Maybe looking into the source code of other packages that do that could be a starting point.
