### ISSUE TITLE
Issue of JOS3: NaN values when "female" is selected.

### ISSUE THREAD

**Issue by AkihisaNomoto** [CenterForTheBuiltEnvironment/pythermalcomfort#115]
@AkihisaNomoto will deal with this issue. Here is an email from a person.

> Specifically, when using the pythermalcomf package, we observed that some conditions returned NAN values for skin temperatures in cases where the sex was set to "female." While some data for females were successfully predicted, the errors we encountered were exclusively related to this sex. Additionally, when we ran the example provided on the pythermalcomf page and changed the sex to "female," the output also resulted in NAN values for skin temperatures. However, when using the code linked to the JOS-3 paper, the female data was successfully predicted without any issues.

**Comment by AkihisaNomoto** [comment]
Hi @FedericoTartarini, 

I just finished fixing this issue and pushed it to the development branch. I think I should have made a different branch and done a pull request so that you could easily review my changes, but it was a quick fix so it would be fine. I hope this change will be merged into the main branch once the work that your students are working on is completed. 

Let me know if you find any problems.

Thanks,
Aki

**Comment by FedericoTartarini** [comment]
@AkihisaNomoto thank you for working on this, yes in the future it would be better if you do not change the code directly in `development`. A pull request would have been much better. But do not worry, for this time it is fine.
