### ISSUE TITLE
Humidity differences in py and r

### ISSUE THREAD

**Issue by Wangjiayi1115** [CenterForTheBuiltEnvironment/pythermalcomfort#119]
## Describe the bug
Here are the differences we have identified:

- [ ] calculation of humidity

# *humidity*

In py the calculation is [link](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/496f3799de287737f2ea53cc6a8c900052a29aaa/pythermalcomfort/models/humidex.py#L44)

`hi = tdb + 5 / 9 * ((6.112 * 10 ** (7.5 * tdb / (237.7 + tdb)) * rh / 100) - 10)`

In R the calculation is [link](https://github.com/marcelschweiker/comf/blob/cece40585bb35baa325435cedc03030b65e69337/R/calcHumidity.R#L78)

`ta+5/9*(6.11*exp(5417.753*(1/273.15-1/(calcDewp(ta, rh)+273.15)))-10)`

R Implementation:
The calculation uses the dew point temperature (calcDewp) as an intermediate step.This approach is based on the Clausius-Clapeyron equation, leveraging the dew point to determine vapor pressure before calculating the Humidex.

Python Implementation: 
The calculation skips the dew point temperature and directly computes the saturated vapor pressure using Tetens’ formula.
It simplifies the process by directly using the dry bulb temperature and relative humidity to calculate vapor pressure.
@FedericoTartarini and Marcel to review

**Comment by FedericoTartarini** [comment]
@Wangjiayi1115 precision and attention to details is very important. 
1. This function is not called humidity but instead it is called humidex.
2. From this pull request it is also not clear to me if this affects the results.

The rest of the pull request is great since it describes the issue.

Marcel, I cannot tag you again in this issue. 

I am using the code from:
<img width="479" alt="image" src="https://github.com/user-attachments/assets/4e467d64-d445-4593-94eb-d5a011efdef5">

Where did you get your equation?

**Comment by marcelschweiker** [comment]
Mine was implemented by a colleague from Karlsruhe. He used Masterton and Richarddson (1979)
![image](https://github.com/user-attachments/assets/a790fb63-df99-4ca2-bb87-13e2bffbacad)
So, we have two options to proceed:
a) add the other version to each package to have two versions each and clarify which is which by giving them unique names.
b) change R to be in line with py as you used a more up-to-date version
I am fine with both and lean towards b.

**Comment by FedericoTartarini** [comment]
As you proposed in option a) we can keep both equations. In python, I will add an input to the humidex function similar to what I did for the PMV model
`pythermalcomfort.models.pmv.pmv(tdb, tr, vr, rh, met, clo, wme=0, standard='ISO', units='SI', limit_inputs=True, airspeed_control=True)`
In this case I will call it model and by defalt will be set to "rana" the other option will be "masterton". In the documentation I will also provide additional informations about the models

**Comment by marcelschweiker** [comment]
Sounds good. Suggest then the same approach for R, i.e. having two alternatives and selection via "model" variable

**Comment by FedericoTartarini** [comment]
@marcelschweiker I have implemented this functionality and added the masterson formulation to pythermalcomfort. See example below.

```
result = humidex(tdb=25, rh=50)
print(result.humidex)  # 28.2 results using the rana model which is the default

result = humidex(tdb=21, rh=100, model="masterson")
print(result.humidex)  # 29.3
```

I am therefore closing this issue. Please open one in your GitHub repository if you have not implemented this feature yet in R.
