### ISSUE TITLE
Add UTCI stress categories

### ISSUE THREAD

**Issue by grjonathan** [CenterForTheBuiltEnvironment/pythermalcomfort#12]
Could models.utci also return the UTCI stress category (e.g. strong heat stress)?  There is a table with the ranges in [Zare et al. (2018)](https://doi.org/10.1016/j.wace.2018.01.004).

**Comment by FedericoTartarini** [comment]
Hi, this can surely be done, however, I have had a look at the [UTCI official tool](http://www.utci.org/index.php) but the tool does not return the same categories as shown in Table 2. See screenshot below.

![image](https://user-images.githubusercontent.com/40018640/116970248-35362e00-acea-11eb-9ce9-bd60cda2541c.png)

**Comment by grjonathan** [comment]
You are correct, it is not a return from the official tool. However, if you look in the [documents section](http://www.utci.org/utci_doku.php) of that same page you will see the categories in "UTCI Assessment Scale.doc". 
I believe the scale originally appeared in [this paper by  Blazejczyk et al.](https://www.researchgate.net/publication/239525964_An_introduction_to_the_Universal_Thermal_Climate_Index_UTCI)

![image](https://user-images.githubusercontent.com/51000403/117087286-fbcae600-ad1c-11eb-86a1-bfc73eaaeb11.png)

**Comment by FedericoTartarini** [comment]
Thank you a lot for providing the code and helping me with this. 

I have released a new version of pythermalcomfort which now includes your code. I have only made one small change and renamed one of the key (`stress_category`) that is returned by the UTCI function.

**Comment by grjonathan** [comment]
Great, thanks for adding it!
