### ISSUE TITLE
Wind chill differences in Python and R

### ISSUE THREAD

**Issue by number9527-12** [CenterForTheBuiltEnvironment/pythermalcomfort#124]
**Describe the bug**
Here are the differences we have identified：
- [ ] Calculation of `Wind Chill Index (WCI)` in Python
- [ ] Calculation of `Wind Chill Temperature (TWC)` in R

### `Wind Chill Index (WCI)` in Python
---
#### In Python, the function is [link](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/496f3799de287737f2ea53cc6a8c900052a29aaa/pythermalcomfort/models/wc.py#L48C5-L48C49): 
```python
wci = (10.45 + 10 * v**0.5 - v) * (33 - tdb)
```
The result is calculated in W/m² and considers the heat loss from a cylindrical flask.

### `Wind Chill Temperature (TWC)` in R
---
#### In R, the function is [link](https://github.com/marcelschweiker/comf/blob/cece40585bb35baa325435cedc03030b65e69337/R/calcTWC.R#L21):
```r
twc = 13.12 + 0.6215 * ta - 11.37 * (v^0.16) + 0.3965 * ta * (v^0.16)
```
The result is given in °C, representing the localized cooling effect on skin due to wind.

@FedericoTartarini and Marcel to review
Should we make modifications to the corresponding function file calcTWC.R in the R package?

**Comment by marcelschweiker** [comment]
I believe that these two parameters sound similar, but are actually different concepts. py seems to refer to AHSRAE, while R to ISO

**Comment by FedericoTartarini** [comment]
I have implemented in Python and I will include it in v.3
