### ISSUE TITLE
UTCI differences between R and Python

### ISSUE THREAD

**Issue by number9527-12** [CenterForTheBuiltEnvironment/pythermalcomfort#126]
**Describe the bug**
We have identified a discrepancy in the input validation for the **Universal Thermal Climate Index (UTCI)** between the R and Python implementations:

- **R implementation**: The wind speed range is **0 to 10 m/s**.
- **Python implementation**: The wind speed range is **0.5 to 17 m/s**.

#### **UTCI in R**
In the R implementation, the `validateUTCI()` function checks if the wind speed is within the range of **0 to 10 m/s**. Any input outside this range is considered invalid. Here's the relevant part of the code[link](https://github.com/marcelschweiker/comf/blob/cece40585bb35baa325435cedc03030b65e69337/R/utils-validator.r#L23C3-L23C25):

```R: 
checkRange(vel, 0, 10)
```

#### **UTCI in Python**
In Python, the line is [link](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/496f3799de287737f2ea53cc6a8c900052a29aaa/pythermalcomfort/models/utci.py#L114):
```Python 
v_valid = valid_range(v, (0.5, 17.0)) -[]
```
Because wind speeds exceeding 10 are not supported in R, we skipped some test cases during testing. The calculation results of the two function files on other test cases are consistent, but there are some differences in the parameter range.
@FedericoTartarini and Marcel to review.

**Comment by FedericoTartarini** [comment]
@marcelschweiker I checked on the [UTCI official calculator](https://www.utci.org/utci_calc.php) and the upper limit for wind speed is 17m/s. In addition, the lower limit should be 0.5 m/s. Is it okay if we change the upper and lower limits in R?

**Comment by marcelschweiker** [comment]
yes, fine for me. Maybe my limits are based on previous more limited version. Thanks for identifying the discrepancy

**Comment by FedericoTartarini** [comment]
@number9527-12 could you please:
* update the UTCI function in comf
* make sure the tests are all passing

**Comment by number9527-12** [comment]
Hi @FedericoTartarini ,

I have updated the UTCI function in the R implementation to align with the Python implementation by adjusting the wind speed range to 0.5 - 17 m/s. All relevant tests have passed successfully.
