### ISSUE TITLE
solar gain differences in Py and R.

### ISSUE THREAD

**Issue by TwinGan** [CenterForTheBuiltEnvironment/pythermalcomfort#136]
1. variable `fp_table` definitions not the same

[The value of fp_table in Py](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/496f3799de287737f2ea53cc6a8c900052a29aaa/pythermalcomfort/models/solar_gain.py#L106C5-L106C13)

[The value of tp_table in R](https://github.com/TwinGan/comf/blob/20b45b69a7479a2cc5d2c0236dac63c492df144d/R/utils-fctHelp.r#L324)

2. The formula for `e_direct` is not same

R: [e_direct <- fp * solTrans * fBes * solRadDir](https://github.com/TwinGan/comf/blob/20b45b69a7479a2cc5d2c0236dac63c492df144d/R/utils-fctHelp.r#L390)
Python: [e_direct = f_eff * fp * sol_transmittance * f_bes * sol_radiation_dir](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/496f3799de287737f2ea53cc6a8c900052a29aaa/pythermalcomfort/models/solar_gain.py#L167)

There is an f_eff in Python code

@FedericoTartarini  and @marcelschweiker to review

**Comment by marcelschweiker** [comment]
The code for calcSolarGain was provided by a previous student based on pythermalcomfort package. Potentially there have been updates in py since first implementation in R and I trust that the py-version is correct.
Therefore, adjustments can be made in R-code to align with py.
@FedericoTartarini : we may need to define a way to inform the other package whenever updates are done.

**Comment by FedericoTartarini** [comment]
@marcelschweiker yes, I agree, from now moving forward we should define a standardised way to communicate changes in the codebase. I think we can use GitHub and tag each other when we make changes, like you did in the athb. Now that we have the shared validation tables, making a change will also trigger an error, consequently, even if we fail to communicate well this will at least point out that the code is different.
