### ISSUE TITLE
Phs differences in Py and R.

### ISSUE THREAD

**Issue by TwinGan** [CenterForTheBuiltEnvironment/pythermalcomfort#139]
Though I implemented the phs() function in R, the accuracy of decimals still raises some questions.
1. d_lim_loss_50
2. water_loss
3. water_loss_watt

Because the values ​​of these three variables are relatively large, the errors caused by the accuracy of decimals are likely to exceed the tolerance range after multiple loops.

The value of sw_tot_g(water_loss) in 10 iteration in R:
![image](https://github.com/user-attachments/assets/118744ca-bae8-4304-a896-e722c57e9430)
In Python:
![image](https://github.com/user-attachments/assets/ba724003-eb70-49e3-8656-96466277588f)
@FedericoTartarini  and @marcelschweiker please review this question
I suggest increasing the tolerance value if it is acceptable.

------------------------------------------------------------------------------------------------------------------
Besides, in all 10 test cases.
`t_re` has two failed
1. Failed at data row 4 error key: t_re expected output: 37.7 real output: 37.4321946704619
2. Failed at data row 5 error key: t_re expected output: 41.2 real output: 40.5366222295829

the `d_lim_t_re` is also different twice times, which is the variable to record the iteration number of `t_re` exceeding 38

1. Failed at data row 3 error key: d_lim_t_re expected output: 75 real output: 74
2. 1. Failed at data row 5 error key: d_lim_t_re expected output: 57 real output: 68

**Comment by FedericoTartarini** [comment]
@TwinGan thank you for working on this. I will review this issue in the coming days, I also would like to let you know that I chaged some tolerance and some var names in the validation table, please have a look at my pull requests

**Comment by TwinGan** [comment]
> @TwinGan thank you for working on this. I will review this issue in the coming days, I also would like to let you know that I chaged some tolerance and some var names in the validation table, please have a look at my pull requests

I found those updated and we have synchronized to our forked project. Please inform us if any calculation logic changes in code like phs().

**Comment by FedericoTartarini** [comment]
@TwinGan the only changes I made are that now all the functions in python return a dataclass. I have not implemented this functionality yet in all the functions but I am working on it and soon it will be done, but it is not affecting the tests in pythermalcomfort.

**Comment by FedericoTartarini** [comment]
@TwinGan thank you so much for working on this. It is very strange that we get such different results just due to the rounding in python and R. If this is the case, I would argue that we should not implement the function in R and R users should be using pythermalcomfort to calculate the PHS so they get consistent results. I know that people can simply run python code in R, hence, this should not a big problem for R users. @marcelschweiker what do you think?

**Comment by marcelschweiker** [comment]
Interesting observation. I wouldnt agree to loose this functionality in R.
How do we know whether py leads to better rounded results than R?
If not done, I suggest to first compare the output of both py and R to some reference values from a standard or publication published elsewhere. I know this page https://www.eat.lth.se/fileadmin/eat/Termisk_miljoe/PHS/PHS.html , which mentions Appendix E of ISO 7933. I can download ISO 7933 one of the next days, when I find time in the office

**Comment by marcelschweiker** [comment]
Small addition, just remembered, that I added the reference table from ISO 7933 to the R package. You can access via: data(dfISO7933AppF)
Still, I will do a quick check soon, whether the values are still up-to-date

**Comment by FedericoTartarini** [comment]
@marcelschweiker I validated the python code using the table in the ISO standard and the results were matching. Is the PHS code already in R? If yes, then I would not reccommend removing it. However, if this is not the case and @TwinGan has converted the Python code to R, I would recommend just keeping the python version of the code.

**Comment by marcelschweiker** [comment]
@FedericoTartarini  Yes, the PHS code is already in R - function calcIso7933
Let me check the code myself in comparison to py to see whether there is sth I can spot that explains the difference

**Comment by FedericoTartarini** [comment]
@marcelschweiker so sorry, I did not know that it was already there, @TwinGan we should then do not remove it. The student also looked into the two-node model and they have identified that the discrepancies in the results are caused by the different rounding between R and Python. I am sure there must be a solution to this issue, but unfortunately I am not sure how to solve it. 

Marcel please let me know if you find differences in the code or if you find how we can avoid the rouding errors.

**Comment by marcelschweiker** [comment]
@FedericoTartarini I searched a bit and found this article, which describes the problem with rounding in R and also mentions py. Seems an inherit aspect of them following different standards in dealing with 0.5 rounding (not sure if that is only an example or the only case). They also mention py using different rounding methods in py numpy (np.round) and py build-in-function (round). 
https://r-craft.org/rounding-in-r-common-data-wrangling-frustrations-and-workarounds-in-r-julia-and-python/
While annoying, it is also a very interesting observation. I am not sure whether we can find a quick fix or need an MSc student  or so with more time to look into it? Could be a nice publication...

**Comment by FedericoTartarini** [comment]
@marcelschweiker thank you for sharing this with me but I do not think this is what it is causing the issue. I am not using the round function within the PHS code, I am only using it at the end. 

@TwinGan has highlighted that when they are printing the intermediate results in python and R the two store a different number of decimals, however, this could only be a feature of the print function in R and Python. What I mean is that the print function only shows a certain number of decimals but both languages perform the calculation with more digits than those displayed by the print functions. 

@TwinGan why there are some small differences between R and Python already from the first iteration? Do you know at which points the two numbers start diverging? Is the code the same?

**Comment by TwinGan** [comment]
@FedericoTartarini and @marcelschweiker 
Sorry, I just found that the code input  `posture`  has been changed from 1 and 2 to string ("standing", "sitting", "crouching"), which makes R test code meet some problems.

The main differences were actually caused by the `a_r_du` initial logic.

After I fixed this problem, the test result now is:
![image](https://github.com/user-attachments/assets/09742e81-ace5-4d07-aaca-833352790ea3)

There are only two failures.
1.  d_lim_loss_50
for  inputs
{
    "tdb": 40,
    "tr": 40,
    "rh": 33.85,
    "v": 0.3,
    "met": 2.58,
    "clo": 0.5,
    "posture": "standing"
}
2. d_lim_t_re
for inputs
{
    "tdb": 35,
    "tr": 35,
    "rh": 71,
    "v": 0.3,
    "met": 2.58,
    "clo": 0.5,
    "posture": "standing"
}

**Comment by FedericoTartarini** [comment]
@TwinGan I changed that since using a number for the posture is not very intuitive, is this okay? Can you change the test in R or shall we revert to having a number as an input?

@TwinGan are all the tests passing?

@TwinGan and @marcelschweiker if all the tests are passing for the PHS model it means that the internal rounding is not an issue and, therefore, for example, if we get differences in the results of the two-node model is due to the fact that the equations are not the same.

**Comment by FedericoTartarini** [comment]
@marcelschweiker I used the PHS code in the 7933 2004 version. 

@TwinGan has noticed that the PHS code in R is much simpler and there is less iterations so he rewrote the function and called it calcPhs.R could you please have a look and let us know your thoughts. 

The new version that @TwinGan wrote is passing all the tests.
