### ISSUE TITLE
Difference between function calctAdaptASHRAE in the file calcAcomf.R and function adaptive_ashrae.py

### ISSUE THREAD

**Issue by LeylayqZhang** [CenterForTheBuiltEnvironment/pythermalcomfort#140]
The formula for calculating t_cmf in adaptive_ashrae.py is t_cmf = 0.31 * t_running_mean + 17.8, while the formula for calculating tAdaptASHRAE in calcAcomf.R is tAdaptASHRAE = 0.33*tmmo + 17.8, making the first 8 tests failing. The coefficient in those two equation should be the same, either 0.31 or 0.33.
Also, the last 2 tests in test_calctAdaptASHRAE.R failed because calcAcomf.R didn't set the valid range (10.0, 33.5) for the input as the line 152 in adaptive_ashrae.py.

**Comment by FedericoTartarini** [comment]
@marcelschweiker in the ASHRAE 55 2023 the equation uses 0.31 as regression coefficient. May I ask you why you are using 0.33? Are you using another document as a reference? What range did you use, the ASHRAE 55 2023 specifies that the model is only applicable between 10 and 33.5

![image](https://github.com/user-attachments/assets/f55103bb-6ba8-479b-9c6d-d26bf4bea368)

![image](https://github.com/user-attachments/assets/912bb68b-bdbd-4d4d-95c4-a9866379af9b)

**Comment by marcelschweiker** [comment]
@FedericoTartarini I am afraid this is a copy-past error from the equation from the European version.
I verified the source and it should be changed in R

**Comment by FedericoTartarini** [comment]
@LeylayqZhang could you please fix this in R?

**Comment by LeylayqZhang** [comment]
> @LeylayqZhang could you please fix this in R?

done :)

**Comment by FedericoTartarini** [comment]
@LeylayqZhang thank you so much. Have you submitted a pull request to R? If so please close this issue.
