### ISSUE TITLE
Difference between calctAdapt15251 in calcAcomf.R and function adaptive_en.py

### ISSUE THREAD

**Issue by LeylayqZhang** [CenterForTheBuiltEnvironment/pythermalcomfort#141]
the first tests in test_calctAdapt15251.R failed because calcAcomf.R didn't set the valid range (10.0, 33.5) for the input as the line 114 in adaptive_en.py.

**Comment by FedericoTartarini** [comment]
Could you plase provide a bit more information about the issue and show how we can fix it?

**Comment by FedericoTartarini** [comment]
@LeylayqZhang why did you open two issues containing the same information?

**Comment by LeylayqZhang** [comment]
> @LeylayqZhang why did you open two issues containing the same information?

Two issues are for two different functions, although they have the same problem, which is they don't have the valid range (10.0, 33.5) for the input.
The solution is to add the valid range (10.0, 33.5) for the input trm in the function calctAdapt15251 and the input tmmo in the function calctAdaptASHRAE.

**Comment by FedericoTartarini** [comment]
In future, please only mention a single issue in each GitHub issue. The title of the issues was not very clear. @marcelschweiker are you okay if we add a valid range to the adaptive functions?

**Comment by marcelschweiker** [comment]
yes, happy to have this implemented

**Comment by FedericoTartarini** [comment]
@LeylayqZhang could you please make the necessary changes?

**Comment by LeylayqZhang** [comment]
well fixed :) should I merge those functions and tests into marcel's branch straight away or shall I merge into Chongyu's first?

**Comment by FedericoTartarini** [comment]
@LeylayqZhang thank you for doing that. I think you can open a pull request to comf directly, but please discuss this first with Chongyu
