### ISSUE TITLE
Differences between cooling_effect.py and calcCE.R

### ISSUE THREAD

**Issue by number9527-12** [CenterForTheBuiltEnvironment/pythermalcomfort#142]
Here are the differences we found between the Python package and the R package for calculating the cooling effect:

### Determination of wind speed conditions
 In python, When the wind speed is less than or equal to 0.1 m/s, the cooling effect is directly returned to 0. [link](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/496f3799de287737f2ea53cc6a8c900052a29aaa/pythermalcomfort/models/cooling_effect.py#L92)
``` python
    if vr <= 0.1:
        return 0
``` 
In R, A wind speed threshold of 0.2 m/s is used, if the wind speed is below this value, the cooling effect is 0. [link](https://github.com/marcelschweiker/comf/blob/cece40585bb35baa325435cedc03030b65e69337/R/calcCE.R#L24)

``` R
   if (vel <= 0.2){
   ce = 0
   warning('For velocity less than or equal to 0.2, cooling effect is Zero')
   print(paste0("Cooling Effect: ", ce ))
  }
```

### Calculation logic of cooling effect
In python, Use the scipy.optimize.brentq function to perform a bisection root search in the interval [0, 40]. [link](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/496f3799de287737f2ea53cc6a8c900052a29aaa/pythermalcomfort/models/cooling_effect.py#L130C9-L130C48)
``` python 
ce = optimize.brentq(function, 0.0, 40)
```
In R, Use a custom bisect function to perform a bisection root search in the interval [0, 15] [link](https://github.com/marcelschweiker/comf/blob/cece40585bb35baa325435cedc03030b65e69337/R/calcCE.R#L43C7-L43C26)
``` R
ce = bisect(f,0,15)
```
The Python version searches in the interval [0, 40], while the R version searches in the interval [0, 15]. This may cause the R version to fail to find the solution correctly at higher temperature differences. I did reduce the number of cases where I failed after changing to [0, 40] in R.

### Output issues

In python, Use the round() function to round the result to two decimal places. [link](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/496f3799de287737f2ea53cc6a8c900052a29aaa/pythermalcomfort/models/cooling_effect.py#L146)
``` python
return round(ce, 2)
```
In R, The ce value is not returned, so there will be some problems when testing. We have corrected it and kept it consistent. [link](https://github.com/marcelschweiker/comf/blob/cece40585bb35baa325435cedc03030b65e69337/R/calcCE.R#L44)
```  R
print(paste0("Cooling Effect: ", lapply(ce, round,2)))
```

**Comment by FedericoTartarini** [comment]
@marcelschweiker in the 2024 version of the ASHRAE 55 the wind speed has been changed to 0.1m/s therefore we should update it in R.

**Comment by marcelschweiker** [comment]
@FedericoTartarini Yes, agree

**Comment by FedericoTartarini** [comment]
@number9527-12 could you please implement the changes?

**Comment by FedericoTartarini** [comment]
@marcelschweiker I would like to check with you that this code change has been implemented and all tests pass in comf.

**Comment by marcelschweiker** [comment]
Thanks @FedericoTartarini 
I accepted the pull request.
Will need to do the tests at later stage
