### ISSUE TITLE
SET does not work for cold periods

### ISSUE THREAD

**Issue by amitche8** [CenterForTheBuiltEnvironment/pythermalcomfort#149]
Hi, very useful tool! I have one small request, when using the SET model, _pythermalcomfort.models.set_tmp()_, it gives me a nan for cold temperature values. I tried a DB and MRT of 0C, and got a nan. E+ calculates SET for cold temperatures, so I am curious as to what limits are baked into the tool, and if it is possible to get them removed, or a sperate SET function for cold conditions.

Thanks!

**Comment by FedericoTartarini** [comment]
Hi, it returns an np.nan since the input are outside the ASHRAE 55 limits. You can get the SET for colder temperatures by passing `limit_inputs=False`.

```set_tmp(tdb=0, tr=25, v=0.1, rh=50, met=1.2, clo=0.5, limit_inputs=False)```
