### ISSUE TITLE
add Tanabe 65 node model ?

### ISSUE THREAD

**Issue by oylinv** [CenterForTheBuiltEnvironment/pythermalcomfort#17]
Hi, developer.

First of all, thank you for your efforts, providing us with such a simple tool to calculate thermal comfort index, my friends and I have benefited a lot, and sincerely thank you for your efforts.

Second, is it possible to add the Tanabe 65 node model to this awesome package? The calculation code of this model has been developed by Auckland Bioengineering Institute, and this is their repository: https://github.com/ABI-Software/abics. and the code: https://github.com/ABI-Software/abics/blob/master/thermoregulation/Tanabe65MN.py

Thank you again for your efforts! By the way，we will cite you when we publish.

**Comment by FedericoTartarini** [comment]
Hi, I am glad you found pythermalcomfort useful.

I would love to add the Tanabe 65 node model to pythermalcomfort, I just need to check with the authors of the ABI-Software that I can re-use their code. Do you happen to know the authors?

**Comment by oylinv** [comment]
> Hi, I am glad you found pythermalcomfort useful.
> 
> I would love to add the Tanabe 65 node model to pythermalcomfort, I just need to check with the authors of the ABI-Software that I can re-use their code. Do you happen to know the authors?

I regret that I don’t have the author’s contact information, I know this repository because: https://doi.org/10.5334/jors.288, maybe the author can be contacted through this article

**Comment by oylinv** [comment]
thansk a lot for your effort

**Comment by FedericoTartarini** [comment]
I have included the JOS-3 model inside pythermalcomfort
