### ISSUE TITLE
temperature of thermal comfort (t_cmf ) models.adaptative_en line 947

### ISSUE THREAD

**Issue by simonmarti1992** [CenterForTheBuiltEnvironment/pythermalcomfort#18]
Hello
First of all, congrats for this great package which is very useful.
I have a little question concerning the temperature of themal comfort in the adaptative_en function.
It is wrote :
t_cmf = 0.33 * t_running_mean + 18.8
So if I consider a constant running mean temperature of 20°C, I obtain t_cmf = 25.4 °C. I'm a bit surprised by such a high value...
Am I doing something wrong ? 
Best regards
Simon MARTINEZ

**Comment by FedericoTartarini** [comment]
Hi Simon, no that is correct, see the chart below from the CBE Thermal Comfort Tool. I would encourage you to use the PMV or SET model instead of the adaptive model.

![image](https://user-images.githubusercontent.com/40018640/145138807-ec6302e7-9a10-4fb7-aafa-1790adaffff9.png)
