### ISSUE TITLE
Calculate MRT from climate model output?

### ISSUE THREAD

**Issue by milankl** [CenterForTheBuiltEnvironment/pythermalcomfort#2]
Hey @FedericoTartarini, great package!

I'm looking for a way to calculate UTCI from [ERA5](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-land?tab=overview) data. To do that, I need to get the mean radiant temperature from the radiation fluxes provided by ERA5, available are

-  Forecast albedo
- Surface latent heat flux
- Surface net solar radiation
- Surface net thermal radiation
- Surface sensible heat flux
- Surface solar radiation downwards
- Surface thermal radiation downwards

Do you have experience how to do that, maybe already written some functions?

**Comment by FedericoTartarini** [comment]
Hi, I am very happy you find the package useful. 

Unfortunately, I have not done it before, however, you can start by looking at the [ERF function](https://pythermalcomfort.readthedocs.io/en/latest/reference/pythermalcomfort.html#solar-gain-on-people) which estimates the effects of solar radiation on human heat gain and comfort indoors. [Link to the paper](https://escholarship.org/uc/item/89m1h2dg).

There may also be some other papers already published on this topic. Kindly share your findings with me if possible, so we may add a function to this package, if need be.

**Comment by milankl** [comment]
Yeah, I haven't really worked on this before... For the UTCI do you use the polynomial approximation? Apparently, there are three different ways to calculate it, with different speeds & accuracies as shown in Fig. 2 of [this poster](http://utci.org/utci_poster.pdf)

**Comment by FedericoTartarini** [comment]
Chris Mackey originally wrote the UTCI equation in Python and he used the code that it is available [here](http://www.utci.org)

**Comment by milankl** [comment]
You mean the .f90 implementation somewhere on that website? Yes, that uses the polynomial approximation.

**Comment by FedericoTartarini** [comment]
Yes, I refer to the .f90 file.

**Comment by milankl** [comment]
This [dataset](https://cds.climate.copernicus.eu/cdsapp#!/dataset/derived-utci-historical?tab=overview) already includes the MRT for my purpose (and contains UTCI as well). I will contact the authors on details of the calculation, and let you know in case you want to implement them into your package.

**Comment by milankl** [comment]
Okay this calculation is described [here](https://link.springer.com/content/pdf/10.1007/s00484-020-01900-5.pdf) in case you want to add it. It requires a handful of radiative fluxes and location and time of day for some angles, which I guess is already part of some other functions.

**Comment by FedericoTartarini** [comment]
Thank you so much for letting me know and for sharing the link with me.
