### ISSUE TITLE
integration scheme for SET

### ISSUE THREAD

**Issue by eddes** [CenterForTheBuiltEnvironment/pythermalcomfort#20]
Hello (again) there,

This issue deals with the integration scheme in the `set_optimized` function.
The current integration scheme for the core and skin temperatures is Euler's explicit scheme for time discretisation: simple and efficient.

However using this scheme for the physiological two-node model raises two issues:
    - The non-linearity of coefficients in the two-node model imposes a time step smaller than the 60 seconds used in the explicit scheme  (at first sight dt=10 s seems to work), or the use of an implicit scheme (e.g. Crank-Nicolson or full implicit - see first picture below)
    - Euler's scheme is prone to instabilities when the individual is exposed to elevated temperatures (see second picture below)

I would hence suggest going for the full implicit scheme with 60 s time step (paper in preparation) to avoid 
    a) instabilities for specific ambient conditions
    b) looping over 60x60 seconds rather than 10x360 seconds

This can be done with scipy's fsolve: would it be of any interest for the pythermalcomfort project?

Best regards,
Edouard

![Tskin_schemes](https://user-images.githubusercontent.com/8697654/154278393-49fc5d58-f670-487e-bfd9-1e310576b23c.png)
![Tskin_oscillations](https://user-images.githubusercontent.com/8697654/154278421-6efab8e6-53db-424e-ba40-fdc11a43ce43.png)

**Comment by FedericoTartarini** [comment]
Hi Edouard it would be great if we could organize a meeting in which we can discuss in detail this issue. You can reach me at federicotartarini@gmail.com

**Comment by FedericoTartarini** [comment]
@eddes I did not hear back from you.

**Comment by eddes** [comment]
Hi Federico,
Indeed! I fell behind with this topic and will get in touch soon.
Regards,
Edouard

**Comment by FedericoTartarini** [comment]
HI @eddes I am closing this issue since you last commented in May. Please write a reply if you would like me to open this issue again.
