### ISSUE TITLE
Elevated air speed calculation

### ISSUE THREAD

**Issue by adibantwal** [CenterForTheBuiltEnvironment/pythermalcomfort#21]
Hello!

The ASHRAE Standard 55 2017 & 2020 states that the PMV method is applicable to average air speeds below 0.20 m/s, and we can directly use the PMV code to calculate the PMV value.

When the average air speed is > 0.2 m/s, ASHRAE 55 states to modify the PMV based on the cooling effect obtained from SET calculations.

However, in the pythermalcomfort tool, it seems that when the air speed is greater than 0.1 m/s, the cooling effect is used to modify the PMV:
![PTC](https://user-images.githubusercontent.com/89742738/154416288-d93b3b4a-72e4-482a-a438-ea3fdaf3e0b4.png)

According to the pythermalcomfort tool, the PMV is only applicable for 0.1 m/s, and if the air speed greater, we need to adjust the PMV.

I am not sure if this an unclear understanding from my part,  but could you please help clarify this discrepancy with the ASHRAE Standard? It would be a big help!

**Comment by adibantwal** [comment]
Hi, you mean PMV is applicable for V <= 0.1 m/s right?

**Comment by adibantwal** [comment]
I see! Thanks a lot for the quick response, and for the wonderful pythermalcomfort tool!

**Comment by FedericoTartarini** [comment]
You are welcome, please let me know if you have any other questions.

**Comment by adibantwal** [comment]
Hello @FedericoTartarini , in the pythermalcomfort code we have to use the utility for relative air speed calculation before providing velocity input for calculating the PMV, is that correct? 

On the web version of the calculator the relative air speed is automatically calculated for PMV input, is that correct?
