### ISSUE TITLE
Feature request to include local controls (fans increasing air speed)

### ISSUE THREAD

**Issue by haze1986** [CenterForTheBuiltEnvironment/pythermalcomfort#25]
Hi, this is a very useful tool, I tried to verify the results obtained comparing them with Berkeleys and they seem to be different in the PMV. I cant figure out why but the calculated PMV is the same only when air speed is 0.1 m/s, with or without local control in the interface. Do you know why is that so?
https://comfort.cbe.berkeley.edu/

**Comment by FedericoTartarini** [comment]
When you are calculating the PMV using pythermalcomfort are you calculating the relative airspeed and dynamic clothing as explained in [the documentation](https://pythermalcomfort.readthedocs.io/en/latest/reference/pythermalcomfort.html#predicted-mean-vote-pmv-and-predicted-percentage-of-dissatisfied-ppd)?

I believe, that this is what is causing the issue.

**Comment by haze1986** [comment]
Relative air speeds are the same as metabolic rate = 1.0, this was confirmed using the included v_relative function
Clo_dynamic was also confirmed with your tool

**Comment by haze1986** [comment]
If it helps, I found the calculated SET to be very close to Berkeleys' tool, just 0.1deg C difference. 
Though since they did not show how they arrive at their values it's probably very difficult to troubleshoot, if at all.

**Comment by FedericoTartarini** [comment]
Could you please share the file that you are using? Technically the two tools should output the same results but if you share the file you are using with me I can check what is causing the issue.

**Comment by FedericoTartarini** [comment]
Please also share all the steps you have done so I can recreate the error, if possible also share the Python code

**Comment by FedericoTartarini** [comment]
I am closing the issue since I believe you found what it was causing the issue. Please let me know if you have any additional questions.
