### ISSUE TITLE
Differences in Solar Gain calculation and ASHRAE 55 - 2017

### ISSUE THREAD

**Issue by Barbara-Stickel** [CenterForTheBuiltEnvironment/pythermalcomfort#3]
Hello!

Thank you for this package, it's very helpful!
I have a question concerning the solar gain calculations. I noticed a few differences between the function `pythermalcomfort.models.solar_gain` and the JavaScript code from ASHRAE in Appendix C, and I would like to know if there is a reason for those differences.

Among them:
1.
```
# solar_gain function:
i_diff = 0.2 * sol_radiation_dir

# ASHRAE
var Idiff = 0.175 * sol_radiation_dir * math.sin(alt * DEG_TO_RAD) 
```
2.
```
# solar_gain function
e_direct = fp * sol_transmittance * f_bes * sol_radiation_dir

# ASHRAE
var E_direct = fp * feff * sol_transmittance * f_bes * sol_radiation_dir
```

3. `fp_table` are pretty different for both seating and standing

When I change those 3 points, I find the same results as the table C4-1 Computer Code Validation Table.

Thank you,
Barbara

**Comment by FedericoTartarini** [comment]
Hi, thank you so much for messaging me. 

The ASHRAE 55 2017 contains some errors in the calculation of the ERF. A new Addendum will soon be published which will fix all the errors in the code and the table. 

The correct equation to calculate the ERF is [this one](https://github.com/CenterForTheBuiltEnvironment/comfort_tool/blob/bb7d6e02fd4594a651bce47623e7d8f35df659be/static/js/erf.js#L154) and is the same one used by the CBE thermal comfort tool to calculate the ERF. You can access this tool by visiting this [web-page](https://comfort.cbe.berkeley.edu) and clicking on the button called "Solar gain on occupants".

The JavaScript code and the Python code should be the same and should return the same results.

Kindly let me know if you find any differences.
