### ISSUE TITLE
JOS-3 Solar radiation heat gain

### ISSUE THREAD

**Issue by adibantwal** [CenterForTheBuiltEnvironment/pythermalcomfort#30]
Hi, hope you're well. 

I am exploring the JOS-3 model, and I notice that the code does not seem to consider the solar radiation gain on an occupant. 
Can you comment on this and correct me if I'm wrong?

Thanks in advance,
Aditya

**Comment by FedericoTartarini** [comment]
Hi Aditya,

I did not personally develop the JOS-3 code. I suggest you open an issue directly on [their GitHub repository](https://github.com/TanabeLab/JOS-3/issues) and ask the question directly to the JOS-3 developer. Please copy and paste their answer here, or copy me in the thread, so I can improve the `pythermalcomfort` documentation.

**Comment by adibantwal** [comment]
Sure, thanks!

**Comment by adibantwal** [comment]
Hi, 

I have got a response on their repository. 

https://github.com/TanabeLab/JOS-3/issues/12

"
import jos3
model = jos3.JOS3()
model._set_ex_q("skin", solar_radiation_heat_gain_at_the_skin)

"

It is still not fully closed as I am unsure how to apply the radiation to each body part. I will update once closed. Thank you.

**Comment by FedericoTartarini** [comment]
Thank you so much for sharing this information, please keep me posted.
