### ISSUE TITLE
Error in calculating steady physiological equivalent temperature (PET)

### ISSUE THREAD

**Issue by guoxuerui** [CenterForTheBuiltEnvironment/pythermalcomfort#35]
**Describe the bug**
There's always an error message : unsupported operand type(s) for +: 'netCDF4._netCDF4.Variable' and 'netCDF4._netCDF4.Variable' when using `pythermalcomfort.models.pet_steady` module
The types of the first four input variables, tdb, tr,v,rh are all netCDF4._netCDF4.Variable, however the calculation includes the plus function between two of them.

The error line are indicate below:
1. Go to '[models.py](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/master/src/pythermalcomfort/models.py)'
2. Scroll down to line 3016 ' t_guess = np.array([36.7, 34, 0.5 * (tdb + tr)])'

Haven's found out how to resolve this problem yet, could you help with solving it? Thanks in advance.

**Comment by FedericoTartarini** [comment]
Hi, I cannot recreate your error. If I run the following code I do not get any error messages:

```
>>> from pythermalcomfort.models import pet_steady
>>> pet_steady(tdb=20, tr=20, rh=50, v=0.15, met=1.37, clo=0.5)
18.85
```

Could you please share the Python code you are currently using?

**Comment by guoxuerui** [comment]
Hi, I use .nc file as input
`ncFile = 'T1_300_S2_r2_2020-07-18_14.00.01.nc'`
`ncData = netCDF4.Dataset(ncFile,'a')`
The tdb,tr,rh and v are fetch from the .nc file so they  all are netCDF4._netCDF4.Variable
`v = ncData.variables['RelHum']`
`tbd = ncData.variables['T']`
`tr = ncData.variables['TMRT']`
`rh = ncData.variables['WindSpd']`
