### ISSUE TITLE
Calculate mean radiant temperature?

### ISSUE THREAD

**Issue by MichaelMMS** [CenterForTheBuiltEnvironment/pythermalcomfort#36]
Question: Almost every function needs the mean radiant temperature. But I can not find a function to calculate the mean radiant temperature.
Inputs would be: temperature, humidity, windSpeed ...
Or have I missed something?

Thx Michael

**Comment by FedericoTartarini** [comment]
Hi the function to calculate the mean radiant temperature is located [here](https://pythermalcomfort.readthedocs.io/en/latest/reference/pythermalcomfort.html#pythermalcomfort.psychrometrics.t_mrt) I should move it to the `utilities`. Sorry for that.

**Comment by MichaelMMS** [comment]
Oh, Thank you very much!

**Comment by orcunkoraliseri** [comment]
Do you have any example for mean radiant temperature calculation? For instance, if I do not have globe temperature, can I use a default value? 

Thank you for this great library!

**Comment by FedericoTartarini** [comment]
Hi, indoors you can calculate the mean radiant temperature using to [solar calculator function](https://pythermalcomfort.readthedocs.io/en/latest/reference/pythermalcomfort.html#solar-gain-on-people). I hope this helps.

**Comment by orcunkoraliseri** [comment]
It will be very helpful. I was going to use it for building energy models. Thanks to this function, I can integrate it directly into the model. Thank you so much.

**Comment by jli113** [comment]
page not found
