### ISSUE TITLE
SET limit_inputs 

### ISSUE THREAD

**Issue by nenazarian** [CenterForTheBuiltEnvironment/pythermalcomfort#39]
This is overall a great code but there seems to be an error regarding the input limits of SET. It seems to follow the Ashrae 55 standard Table 7.3.4 which refers to the "Instrumentation Measurement Range and Accuracy" and not the applicability range. In fact, if you look at Table D3 for the validation of SET models, you find that a few options are outside the limit mentioned in this code (for example, temperature=0C and Velocity of 3m/s). This may not have raised an issue for indoor conditions (which I understand is the focus of the authors) but is quite limiting for outdoor settings where the mean radiant temperature often goes beyond 40C.

**Comment by FedericoTartarini** [comment]
Hi, thank you for the feedback. The ASHRAE 55 standard is not very clear regarding the applicability limits of the SET model so I used more conservative values. However, you can circumvent this issue by setting the input variable `limit_inputs = False` in the SET function (please refer to the official documentation for [more information](https://pythermalcomfort.readthedocs.io/en/latest/reference/pythermalcomfort.html#standard-effective-temperature-set)). Kindly let me know if this solves the problem.

**Comment by nenazarian** [comment]
Thanks, Federico. I'd only suggest changing the language in your documentation which indicates ASHRAE 55 limits are as prescribed in the code ("The ASHRAE 55 2020 limits are 10 < tdb [°C] < 40, 10 < tr [°C] < 40, 0 < vr [m/s] < 2, 1 < met [met] < 4, and 0 < clo [clo] < 1.5"). This is in fact not the case (as noted by you here) and can be misleading for those not familiar with the ASHRAE standard. Otherwise, the code runs with the additional setting. 
Cheers, Negin
