### ISSUE TITLE
_UFuncNoLoopError

### ISSUE THREAD

**Issue by FazelGanji** [CenterForTheBuiltEnvironment/pythermalcomfort#40]
Exception has occurred: _UFuncNoLoopError
ufunc 'two_nodes_optimized_return_set' did not contain a loop with signature matching types (<class 'numpy.dtype[int32]'>, <class 'numpy.dtype[int32]'>, <class 'numpy.dtype[float64]'>, <class 'numpy.dtype[float64]'>, <class 'numpy.dtype[float64]'>, <class 'numpy.dtype[float64]'>, <class 'numpy.dtype[int32]'>, <class 'numpy.dtype[float64]'>, <class 'numpy.dtype[int32]'>, <class 'numpy.dtype[int32]'>) -> None
  File "C:\Users\aganji\Desktop\pmv.py", line 27, in <module>
    results = pmv_ppd(tdb=tdb, tr=tr, vr=vr, rh=rh, met=met, clo=clo, wme=0, standard="ASHRAE")

**Comment by FedericoTartarini** [comment]
Hi, sorry for the late reply. Could you please share more information about the error? Another user had a similar error but I was not able to recreate it.

**Comment by FedericoTartarini** [comment]
Maybe is your version of Numpy that is causing the issue. I have tried to run [this code](https://colab.research.google.com/drive/18cVyQlPYl-Wv-mHxSyUQpHMH2LBHSeMU?usp=sharing) on Google Colab but I was not able to recreate the issue.

**Comment by FazelGanji** [comment]
OK thanks for the hint. I used numpy version 1.18.5 ... and it works.

pip install --force-reinstall numpy==1.18.5

**Comment by FedericoTartarini** [comment]
So I guess it is an issue with Numpy. Maybe I should then modify the setup.py of pythermalcomfort and impose that pythermalcomfort requires numpy==1.18.5.

One strage thing is that when I try to install it on Google Colab I do not get any errors.
