### ISSUE TITLE
Returning one value and not two

### ISSUE THREAD

**Issue by FedericoTartarini** [CenterForTheBuiltEnvironment/pythermalcomfort#45]
In the docstring it is mentioned that two parameters are returned but only one is returned. Could you please fix this error and update the docstring?

https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/c847e76471ad6c02548bc2d6458b6b50b51dd098/src/pythermalcomfort/jos3_functions/construction.py#L131

**Comment by AkihisaNomoto** [comment]
Corrected the docstring for calculating local body surface area and modified the valuable name.
