### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by FedericoTartarini** [CenterForTheBuiltEnvironment/pythermalcomfort#46]
Could you please write a short docstring for this function explaining what it does?

https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/c847e76471ad6c02548bc2d6458b6b50b51dd098/src/pythermalcomfort/jos3_functions/matrix.py#L9

**Comment by AkihisaNomoto** [comment]
Deleted sub2whole function because it seems to be no longer used.
