### ISSUE TITLE
Unit

### ISSUE THREAD

**Issue by FedericoTartarini** [CenterForTheBuiltEnvironment/pythermalcomfort#48]
Should not the unit be W/K/m2 or W/(k m2)?

https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/c847e76471ad6c02548bc2d6458b6b50b51dd098/src/pythermalcomfort/jos3_functions/thermoregulation.py#L341

**Comment by FedericoTartarini** [comment]
You could also remove the t_o function from here and add it to `pythermalcomfort/psychrometric/t_o`

**Comment by AkihisaNomoto** [comment]
Modified the unit to W/(m2*K) from W/K.m2.
