### ISSUE TITLE
err_cr is an input but not used in the function

### ISSUE THREAD

**Issue by FedericoTartarini** [CenterForTheBuiltEnvironment/pythermalcomfort#50]
https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/c847e76471ad6c02548bc2d6458b6b50b51dd098/src/pythermalcomfort/jos3_functions/thermoregulation.py#L469

**Comment by AkihisaNomoto** [comment]
Deleted one of the argument (`err_cr`) that is not used in the function in the code and modified the related code.
