### ISSUE TITLE
variable outside a function with no initialisation

### ISSUE THREAD

**Issue by FedericoTartarini** [CenterForTheBuiltEnvironment/pythermalcomfort#51]
https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/c847e76471ad6c02548bc2d6458b6b50b51dd098/src/pythermalcomfort/jos3_functions/thermoregulation.py#L1207

**Comment by AkihisaNomoto** [comment]
Deleted variable outside a function.
