### ISSUE TITLE
tdb is not used

### ISSUE THREAD

**Issue by FedericoTartarini** [CenterForTheBuiltEnvironment/pythermalcomfort#52]
https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/c847e76471ad6c02548bc2d6458b6b50b51dd098/src/pythermalcomfort/jos3_functions/thermoregulation.py#L1470

**Comment by AkihisaNomoto** [comment]
Deleted this function since it is not used anymore.
