### ISSUE TITLE
Remove commented function

### ISSUE THREAD

**Issue by FedericoTartarini** [CenterForTheBuiltEnvironment/pythermalcomfort#53]
Please remove this commented function since it also seems to be very similar to the function below.

https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/c847e76471ad6c02548bc2d6458b6b50b51dd098/src/pythermalcomfort/models.py#L4248

**Comment by AkihisaNomoto** [comment]
Deleted this commented code.
