### ISSUE TITLE
fixed_hc expects two positional arguments but only one is passed

### ISSUE THREAD

**Issue by FedericoTartarini** [CenterForTheBuiltEnvironment/pythermalcomfort#54]
https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/c847e76471ad6c02548bc2d6458b6b50b51dd098/src/pythermalcomfort/jos3_functions/thermoregulation.py#L435

**Comment by AkihisaNomoto** [comment]
Both arguments (hc and v) are used in this function.

**Comment by AkihisaNomoto** [comment]
Sorry I misunderstood. You are right, and I deleted this function before since this `_heat_resistances` function is not directly used to JOS3 class [with bad commit](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/commit/14b55a79bcf4596cf541d96167cc06054eca9474).

**Comment by FedericoTartarini** [comment]
Okay great if you have fixed this issue I will close the issue.
