### ISSUE TITLE
Duplicate of the condition above

### ISSUE THREAD

**Issue by FedericoTartarini** [CenterForTheBuiltEnvironment/pythermalcomfort#55]
https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/blob/c847e76471ad6c02548bc2d6458b6b50b51dd098/src/pythermalcomfort/jos3_functions/thermoregulation.py#L1280

**Comment by AkihisaNomoto** [comment]
Thanks, this is a bad mistake. Fixed if statement.
