### ISSUE TITLE
Potential typo in default globe diameter for t_mrt function

### ISSUE THREAD

**Issue by jarataraj** [CenterForTheBuiltEnvironment/pythermalcomfort#7]
`pythermalcomfort.psychrometrics.t_mrt(tg, tdb, v, d=0.015, emissivity=0.9)`

The default globe diameter in the above function is .015m, or 1.5 cm, but I read that ISO 7726:1998 recommends a standard globe diameter of .15m, or 15cm ([source](https://en.wikipedia.org/wiki/Mean_radiant_temperature)). Perhaps the extra 0 in the function is a typo, and the default globe diameter was intended to be d=0.15?

**Comment by FedericoTartarini** [comment]
Thank you very much for pointing out that issue. I have [fixed the typo](https://pythermalcomfort.readthedocs.io/en/latest/_modules/pythermalcomfort/psychrometrics.html#t_mrt) and released a new version of pythermalcomfort 1.2.2
