### ISSUE TITLE
pythermalcomfort user interface on the web 

### ISSUE THREAD

**Issue by AkihisaNomoto** [CenterForTheBuiltEnvironment/pythermalcomfort#72]
I noticed that pythermalcomfort user interface had changed. Is that your change or just a bug?

contents
![image](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/assets/67300161/1fad0290-a812-4dfb-93b8-85b4790877d4)

pmv model page
![image](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/assets/67300161/f7c2d948-8210-4f70-bb2a-c24dfbba7492)

**Comment by FedericoTartarini** [comment]
I also noticed this. I did not do anything, perhaps sphynx or readthedocs change their default template and now the documentation layout looks different. I will look into it. But from what I can recall from the last time I looked into it, changing the template is more complicated than what I originally thought.
