### ISSUE TITLE
Issue in optimized_functions.two_nodes_optimized (unable to converge tc value for data)

### ISSUE THREAD

**Issue by ProteekChaudhuriBertLabs** [CenterForTheBuiltEnvironment/pythermalcomfort#76]
**Describe the bug**
Code goes to raise StopIteration("Max iterations exceeded") for multiple input data

**To Reproduce**
call the function thermalcomfort_pmv with the following static arguments:

activity = 'Typing'
garments = 'Trousers, short-sleeve shirt, socks, shoes, underwear'

**Expected behavior**
Calculate values of thermal comfort

**Screenshots**
https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort/assets/145983629/26789015-dc25-498e-99a2-e252a2dc20ae

 - OS: Windows 11
 - Version 2.7.2

**Comment by FedericoTartarini** [comment]
@ProteekChaudhuriBertLabs thank you for opening this issue. Could you please provide more information about the issue? See my comments below:

1. `thermalcomfort_pmv` is not a function in pythermalcomfort. Which function did you use? Are you using the pmv_ppd function? 
2. which ta, tr, v, rh values did you use?
