### ISSUE TITLE
numpy round vs round_

### ISSUE THREAD

**Issue by ibrahimmudassar** [CenterForTheBuiltEnvironment/pythermalcomfort#84]
**Describe the bug**
DeprecationWarning: `round_` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `round` instead.
  df['utci'] = utci(tdb=df['temperature_2m'], tr=df['apparent_temperature'],

**To Reproduce**
[https://pythermalcomfort.readthedocs.io/en/latest/_modules/pythermalcomfort/models.html#utci](utci)
1. Use the utci function

**Desktop**
 - OS: Windows 10, Python 3.11

**Comment by FedericoTartarini** [comment]
Thank you for opening this issue. I just fixed the error and I am deploying a new version of pythermalcomfort 2.8.9 

I closed the issue since everything should be fine but please let me know if the issue persists.
