### ISSUE TITLE
Documentation improvement: solar gain on people

### ISSUE THREAD

**Issue by grjonathan** [CenterForTheBuiltEnvironment/pythermalcomfort#9]
Awesome package!
I suggest changing the description of sol_azimuth in pythermalcomfort.models.solar_gain to align with the description of Solar horizontal angle relative to the front of the person (SHARP) in ASHRAE 55-2017 Appendix C. The current description seems to imply that the person is always facing North, while it is possible to study other "body azimuths".

**Comment by FedericoTartarini** [comment]
Done, thank you very much for the suggestion, please have a look at the new documentation and please let me know if you spot some mistakes.
